#!/usr/bin/env bash


print_usage () {
    echo -e "Usage:\n$(basename "$0") <UUID>"
}


print_message () {
    local message_type="$1"

    local message="$2"

    if [ "$message_type" == "status" ]; then
        printf "\e[1;34m...%s\e[m\n" "$message"
    elif [ "$message_type" == "success" ]; then
        printf "\e[1;32m%s\e[m\n" "$message"
    elif [ "$message_type" == "error" ]; then
        printf "\e[1;31mError: %s\e[m\n" "$message"
    elif [ "$message_type" == "warning" ]; then
        printf "\e[1;33mWarning: %s\e[m\n" "$message"
    elif [ "$message_type" == "mentor_warning" ]; then
        printf "\e[1;35mMentor notes warning: %s\e[m\n" "$message"
    fi
}


download_solution () {
    local solution_uuid="$1"

    local solution_dir="$(exercism download --uuid="$solution_uuid" 2> /dev/null)"
    
    local download_status="$?"

    if [ "$download_status" -ne 0 ]; then
        echo "Failed to download the exercise. Error code: "$download_status""

        exit 1
    fi

    echo "$solution_dir"
}


clean_solution_files () {
    print_message "status" "Removing the '#[ignore]' lines from the test suite file."

    local exercise_name="${PWD##*/}"

    local test_file="tests/$exercise_name.rs"

    sed -i -e "/ignore/d" "$test_file"

    if [ "$?" -ne 0 ]; then
        print_message "error" "Failed to clean the solution test file. Aborting."

        exit 1
    fi
}


run_rust_tools () {
    print_message "status" "Running tests."

    local test_results="$(cargo test --quiet > /dev/null 2>&1)"

    if [ "$?" -ne 0 ]; then
        print_message "error" "Some tests have failed!"

        printf "%s\n" "$test_results"
    else
        print_message "success" "All the tests have passed!"
    fi

    cargo clean

    print_message "status" "Running clippy."

    local clippy_warnings="$(cargo clippy --quiet > /dev/null 2>&1)"

    if [ -n "$clippy_warnings" ]; then
        print_message "warning" "Clippy has produced some warnings:"

        printf "%s\n" "$clippy_warnings"
    else
        print_message "success" "No clippy warnings."
    fi

    print_message "status" "Running rustfmt."

    cargo fmt -- --quiet --check > /dev/null

    if [ "$?" -ne 0 ]; then
        print_message "warning" "The solution is not formatted according to the rustfmt style guidelines."
    fi
}


occurrences_number () {
    local string="$1"

    local sub="$2"

    local s=${string//"$sub"}

    echo "$((("${#string}" - "${#s}") / "${#sub}"))"
}


analyze_pythagorean_triplet () {
    local solution_path="src/lib.rs"

    local solution="$(<"$solution_path")"

    local mut_num="$(occurrences_number "$solution" "mut")"

    local for_num="$(occurrences_number "$solution" "for")"

    if [ "$mut_num" -gt 1 ]; then
        print_message "warning" "Big number of the mutable variables ($mut_num)."
    fi

    if [ "$for_num" -gt 2 ]; then
        print_message "warning" "Big number of the for loops ($for_num)."
    fi

    echo "$solution" | grep -E "(\b\w+\b) *\* *(\b\1\b)" > /dev/null

    if [ "$?" -eq 0 ]; then
        print_message "mentor_warning" "Found the occurrence of the 'a*a' construct."
    fi

    echo "$solution" | grep -E "\breturn\b *\S+ *;" > /dev/null

    if [ "$?" -eq 0 ]; then
        print_message "mentor_warning" "Found the explicit return statement."
    fi

    if [[ $solution =~ f[63][42] ]]; then
        print_message "mentor_warning" "Found the usage of the f32/f64 type."
    fi
}


analyze_solution () {
    print_message "status" "Analyzing the solution."

    local exercise_name="${PWD##*/}"

    if [ "$exercise_name" == "pythagorean-triplet" ]; then
        analyze_pythagorean_triplet
    else
        print_message "status" "Unknown exercise. Aborting the analysis."
    fi
}


if [ "$#" -ne 1 ]; then
    print_usage

    exit 1
fi

print_message "status" "Downloading the solution."

solution_dir="$(download_solution "$1")"

print_message "success" "Downloaded to $solution_dir."

(
    cd "$solution_dir"

    clean_solution_files

    run_rust_tools

    analyze_solution
)
